name: Tests

on:
  pull_request:
  push:
    branches: [main, test]
  merge_group:

jobs:
  packaging:
    name: Python packaging
    uses: tskit-dev/.github/.github/workflows/python-packaging.yml@main
    with:
      cli-test-cmd: tsdate --help

  test:
    name: Python
    uses: tskit-dev/.github/.github/workflows/python-tests.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python }}
      coverage-directory: tsdate
    secrets: inherit
    strategy:
      matrix:
        python: ["3.11", "3.13"]
        os: [macos-latest, ubuntu-24.04, windows-latest]
